version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend_network
    container_name: sportevents_frontend

networks:
  frontend_network:
    driver: bridge